### ISSUE TITLE
Update Azure AD Pod Identity snippets to use version v1.5.5

### ISSUE THREAD

**Issue by DanielArthurUK** [MicrosoftDocs/azure-dev-docs#182]
Following the [Create an Application Gateway ingress controller in Azure Kubernetes Service Tutorial](https://docs.microsoft.com/en-us/azure/developer/terraform/create-k8s-cluster-with-aks-applicationgateway-ingress) from scratch leaves the AAD Identity Pod stuck in error:

```bash
$ kubectl get pods
NAME                            READY   STATUS             RESTARTS   AGE
ingress-azure-db7567987-rmggj   0/1     CrashLoopBackOff   37         121m
```

This is a known issue: Azure/application-gateway-kubernetes-ingress#838

The workaround suggested is to use version v1.5.5 of the aad-pod-identity, rather than the YAML file on master. For example, under [Install Azure AD Pod Identity](https://docs.microsoft.com/en-us/azure/developer/terraform/create-k8s-cluster-with-aks-applicationgateway-ingress#install-azure-ad-pod-identity), we could specify the version of the YAML file to use (example is RBAC disabled snippet):

```diff
- kubectl create-f https://raw.githubusercontent.com/Azure/aad-pod-identity/master/deploy/infra/deployment.yaml
+ kubectl create -f https://raw.githubusercontent.com/Azure/aad-pod-identity/v1.5.5/deploy/infra/deployment.yaml

```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 549713ae-8a7b-270a-a758-3a439d5518fe
* Version Independent ID: a46c18ff-0092-0384-b1ed-3ec076516da4
* Content: [Tutorial - Create an Application Gateway ingress controller in Azure Kubernetes Service](https://docs.microsoft.com/en-us/azure/developer/terraform/create-k8s-cluster-with-aks-applicationgateway-ingress)
* Content Source: [articles/terraform/create-k8s-cluster-with-aks-applicationgateway-ingress.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/terraform/create-k8s-cluster-with-aks-applicationgateway-ingress.md)
* Service: **terraform**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by TomArcherMsft** [comment]
@DanielArthurUK It looks from https://github.com/Azure/application-gateway-kubernetes-ingress/issues/828 that this issue is resolved. Is that correct?

**Comment by DanielArthurUK** [comment]
Hi @TomArcherMsft it certainly looks that the issue is resolved - I haven't had a chance to try out the new [release candidate](https://github.com/Azure/application-gateway-kubernetes-ingress/releases/tag/1.2.0-rc2) yet. I will see if I can find time over the next couple of days!

**Comment by TomArcherMsft** [comment]
@DanielArthurUK Thanks, I'm going to close this issue for now, but let me know if the problem persists. #please-close

**Comment by madhurichilaka** [comment]
This issue still persists with the combination of 1.2.0-rc3 for AGIC and the latest AAD Pod Identity helm charts on Master. 

### Error:
Readiness probe failed: Get http://10.0.0.19:8123/health/ready: net/http: request canceled (Client.Timeout exceeded while awaiting headers)

### appgw-ingress-azure Logs:

ERROR: logging before flag.Parse: I0706 10:47:53.446521       1 utils.go:115] Using verbosity level 3 from environment variable APPGW_VERBOSITY_LEVEL
I0706 10:47:53.490176       1 environment.go:240] KUBERNETES_WATCHNAMESPACE is not set. Watching all available namespaces.
I0706 10:47:53.490294       1 main.go:128] Appication Gateway Details: Subscription="" Resource Group="" Name=""
I0706 10:47:53.490311       1 auth.go:46] Creating authorizer from Azure Managed Service Identity
I0706 10:47:53.490389       1 httpserver.go:57] Starting API Server on :8123
I0706 10:48:20.405598       1 main.go:175] Ingress Controller will observe all namespaces.
I0706 10:48:20.481759       1 context.go:132] k8s context run started
I0706 10:48:20.481796       1 context.go:176] Waiting for initial cache sync
I0706 10:48:20.581999       1 context.go:189] Initial cache sync done
I0706 10:48:20.582023       1 context.go:190] k8s context run finished
I0706 10:48:20.582202       1 worker.go:39] Worker started
I0706 10:48:20.720432       1 mutate_app_gateway.go:177] BEGIN AppGateway deployment
I0706 10:50:11.693085       1 mutate_app_gateway.go:185] Applied generated Application Gateway configuration
I0706 10:50:11.693108       1 mutate_app_gateway.go:200] cache: Updated with latest applied config.
I0706 10:50:11.693775       1 mutate_app_gateway.go:204] END AppGateway deployment
I0706 10:50:11.693832       1 controller.go:151] Completed last event loop run in: 1m51.111588806s

### NMI Logs
I0706 10:47:04.390212       1 main.go:61] Starting nmi process. Version: 1.6.1. Build date: 2020-05-22-17:50.
I0706 10:47:04.576664       1 crd.go:447] CRD lite informers started
I0706 10:47:04.681124       1 main.go:85] Running NMI in namespaced mode: false
I0706 10:47:04.681164       1 nmi.go:52] Initializing in standard mode
I0706 10:47:04.681172       1 probes.go:42] Initialized health probe on port 8080
I0706 10:47:04.681179       1 probes.go:45] Started health probe
I0706 10:47:04.681264       1 metrics.go:329] Registered views for metric
I0706 10:47:04.681303       1 prometheus_exporter.go:22] Starting Prometheus exporter
I0706 10:47:04.681322       1 metrics.go:336] Registered and exported metrics on port 9090
I0706 10:47:04.681331       1 server.go:97] Listening on port 2579
W0706 10:47:04.694523       1 iptables.go:104] Flushing iptables to add aad-metadata custom chains
E0706 10:47:53.490779       1 client.go:184] pod list empty
W0706 10:47:53.490805       1 client.go:210] List pod error: <nil>. Retrying, attempt number: 1
E0706 10:47:53.790919       1 client.go:184] pod list empty
W0706 10:47:53.790955       1 client.go:210] List pod error: <nil>. Retrying, attempt number: 2
E0706 10:47:54.091141       1 client.go:184] pod list empty
W0706 10:47:54.091177       1 client.go:210] List pod error: <nil>. Retrying, attempt number: 3
E0706 10:47:54.391370       1 client.go:184] pod list empty
W0706 10:47:54.391408       1 client.go:210] List pod error: <nil>. Retrying, attempt number: 4
I0706 10:48:19.692334       1 standard.go:77] clientID in request: 7cb4##### REDACTED #####742f, default/appgw-ingress-azure-664f55496c-wlhzf has been matched with azure identity default/appgw-ingress-azure
I0706 10:48:19.692387       1 standard.go:165] matched identityType:0 clientid:7cb4##### REDACTED #####742f resource:https://management.azure.com/
I0706 10:48:20.144024       1 server.go:191] Status (200) took 26653290027 ns for req.method=GET reg.path=/metadata/identity/oauth2/token req.remote=10.0.0.19

### MIC Logs
I0706 10:47:05.477098       1 main.go:101] Starting mic process. Version: 1.6.1. Build date: 2020-05-22-17:50
W0706 10:47:05.477155       1 main.go:106] --kubeconfig not passed will use InClusterConfig
I0706 10:47:05.477164       1 main.go:120] kubeconfig () cloudconfig (/etc/kubernetes/azure.json)
I0706 10:47:05.477304       1 main.go:128] Running MIC in namespaced mode: false
I0706 10:47:05.477314       1 main.go:132] Client QPS set to: 5. Burst to: 5
I0706 10:47:05.477327       1 mic.go:136] Starting to create the pod identity client. Version: 1.6.1. Build date: 2020-05-22-17:50
I0706 10:47:05.500160       1 mic.go:142] Kubernetes server version: v1.16.9
I0706 10:47:05.500650       1 probes.go:42] Initialized health probe on port 8080
I0706 10:47:05.500665       1 probes.go:45] Started health probe
I0706 10:47:05.500725       1 metrics.go:329] Registered views for metric
I0706 10:47:05.500758       1 prometheus_exporter.go:22] Starting Prometheus exporter
I0706 10:47:05.500764       1 metrics.go:336] Registered and exported metrics on port 8888
I0706 10:47:05.500768       1 mic.go:238] Initiating MIC Leader election
I0706 10:47:05.500784       1 leaderelection.go:242] attempting to acquire leader lease  default/aad-pod-identity-mic...
I0706 10:47:05.532956       1 leaderelection.go:252] successfully acquired lease default/aad-pod-identity-mic
I0706 10:47:05.905624       1 mic.go:311] Upgrading the types to work with case sensitive go-client
I0706 10:47:05.925018       1 mic.go:315] Type upgrade completed !!
I0706 10:47:06.605292       1 pod.go:73] Pod cache synchronized. Took 500.067159ms
I0706 10:47:06.605443       1 crd.go:456] CRD informers started
I0706 10:47:06.605447       1 pod.go:80] Pod watcher started !!
I0706 10:47:06.605467       1 mic.go:393] Sync thread started.
I0706 10:47:39.999842       1 mic.go:1009] Processing node aks-demopool-35064155-vmss, add [1], del [0], update [0]
I0706 10:47:39.999889       1 crd.go:515] Got assigned id appgw-ingress-azure-664f55496c-wlhzf-default-appgw-ingress-azure to assign
I0706 10:47:40.951076       1 cloudprovider.go:208] Updating user assigned MSIs on aks-demopool-35064155-vmss, assign [1], unassign [0]
I0706 10:48:18.516092       1 crd.go:793] Updating assigned identity default/appgw-ingress-azure-664f55496c-wlhzf-default-appgw-ingress-azure status to Assigned
I0706 10:48:18.521990       1 mic.go:514] Work done: true. Found 1 pods, 1 ids, 1 bindings
I0706 10:48:18.522011       1 mic.go:515] Total work cycles: 19, out of which work was done in: 1
I0706 10:48:18.522019       1 stats.go:99] ** Stats collected **
I0706 10:48:18.522024       1 stats.go:82] Pod listing: 10.9µs
I0706 10:48:18.522033       1 stats.go:82] ID listing: 2µs
I0706 10:48:18.522037       1 stats.go:82] Binding listing: 3.1µs
I0706 10:48:18.522041       1 stats.go:82] Assigned ID listing: 500ns
I0706 10:48:18.522045       1 stats.go:82] System: 58µs
I0706 10:48:18.522048       1 stats.go:82] CacheSync: 900ns
I0706 10:48:18.522052       1 stats.go:82] Cloud provider get: 933.553576ms
I0706 10:48:18.522056       1 stats.go:82] Cloud provider put: 37.564958176s
I0706 10:48:18.522060       1 stats.go:82] Assigned ID addition: 17.57205ms
I0706 10:48:18.522063       1 stats.go:82] Assigned ID deletion: 0s
I0706 10:48:18.522067       1 stats.go:89] Number of cloud provider PUT: 1
I0706 10:48:18.522070       1 stats.go:89] Number of cloud provider GET: 1
I0706 10:48:18.522074       1 stats.go:89] Number of assigned ids created in this sync cycle: 1
I0706 10:48:18.522077       1 stats.go:89] Number of assigned ids updated in this sync cycle: 0
I0706 10:48:18.522080       1 stats.go:89] Number of assigned ids deleted in this sync cycle: 0
I0706 10:48:18.522083       1 stats.go:82] Find assigned ids to create: 0s
I0706 10:48:18.522087       1 stats.go:82] Find assigned ids to delete: 0s
I0706 10:48:18.522090       1 stats.go:82] Total time to assign or remove IDs: 38.52214113s
I0706 10:48:18.522094       1 stats.go:82] Event recording: 0s
I0706 10:48:18.522098       1 stats.go:82] Total: 38.522328031s
I0706 10:48:18.522101       1 stats.go:129] *********************
